#pandas basics

In [ ]:
#Series and Dataframe, Loading datasets(csv,Excel), Exploring data(head, info,describe), Indexing & Filtering, Sorting

In [1]:
#Install Pandas
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp312-cp312-macosx_11_0_arm64.whl.metadata (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 885.4 kB/s eta 0:00:00 kB/s eta 0:00:01
Requirement already satisfied: numpy>=1.26.0 in ./venv/lib/python3.12/site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp312-cp312-macosx_11_0_arm64.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 19.0 MB/s eta 0:00:0031m18.0 MB/s eta 0:00:01
Installing collected packages: pandas
Successfully installed pandas-3.0.3

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [2]:
import pandas as pd

#Series and Dataframe
#they are two type of data structure in python 
#like numpy series is 1D and dataframe is 2d
pd.Series() is used to define series
whereas pd.DataFrame() is used to define dataframe
every file either csv, excel, json , api or sql read and loaded in to pandas is stored as dataframe

In [3]:
l = list("KATHMANDU")
l

['K', 'A', 'T', 'H', 'M', 'A', 'N', 'D', 'U']

In [4]:
pd.Series(l)

0    K
1    A
2    T
3    H
4    M
5    A
6    N
7    D
8    U
dtype: str

In [10]:
pd.DataFrame(l, columns=["Values"])

  Values
0      K
1      A
2      T
3      H
4      M
5      A
6      N
7      D
8      U

In [11]:
#Read csv file and excel file

#pd.read_csv is the method used to read csv file
#pd.read_excel is the method used to read excel file

#Read CSV file

In [ ]:
#Syntax:  pd.read_csv(path_to_file)

In [ ]:
path = ""
data_csv = pd.read_csv(path)

#Read excel file
pd.read_excel(path_to_file)

In [13]:
l2 = list("DIPESH")
print(l2)

['D', 'I', 'P', 'E', 'S', 'H']

In [21]:
pd.DataFrame(l2, columns=["Values"])

  Values
0      D
1      I
2      P
3      E
4      S
5      H

In [26]:
#get the sheet name of excel file
shet = pd.ExcelFile(path_excel)
print(shet.sheet_names)

SyntaxError: invalid syntax (4228664250.py, line 3)

In [ ]:
#READ THE SHEET TRANACTIONS

trans = pd.read_excel(path_excel, sheet_name = "transactions")

In [27]:
#Explore Preview Methods (functions)

#head() returns the first fice row of dataset
#tail() returns the last five row of the dataset
#info() returns the name of column, their datatype, not null count and memory occupies
#describe() returns the basic stats of numeric columns
#columns()
#products.columns
#products.shape

In [ ]:
#indexing and filterings

In [28]:
#Filtering: getting rows that fits the condition given
data_csv.head(2)

NameError: name 'data_csv' is not defined

In [29]:
data_csv.info()

NameError: name 'data_csv' is not defined

In [ ]:
#Get all the rows where milage is >=30

con = data_csv['Milage']>=30

In [ ]:
data_csv(con)

In [30]:
#Filter the data where milage>=30 and location is mumbai
con1 = data_csv["Milage"]>=30
con2 = data_csv["Location"] == "Mumbai"
data_csv[con1 & con2]

SyntaxError: unterminated string literal (detected at line 3) (3815893835.py, line 3)

In [ ]:
#Filter the data where milage>=30 or location is mumbai

In [ ]:
con1 = data_csv["Milage"]>=30
con2 = data_csv["Location"] == "Mumbai"
data_csv[con1 | con2]

In [ ]:
#not 
#Filter all the rows where not condition for milage >=30 and location is Mumbai

con1 = data_csv["Milage"]>=30
con2 = data_csv["Location"] == "Mumbai"
data_csv[~(con1 & con2)]

In [31]:
#isin()
data_csv['Location'].unique()

NameError: name 'data_csv' is not defined

In [ ]:
#isin()

locks = ['Mumbai','Pune']